"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const resource_1 = require("./resolve/resource");
exports.ResourceResolver = resource_1.default;
const javascript_1 = require("./resolve/javascript");
exports.JavascriptResolver = javascript_1.default;
const typescript_1 = require("./resolve/typescript");
exports.TypescriptResolver = typescript_1.default;
const image_1 = require("./resolve/image");
exports.ImageResolver = image_1.default;
const option_1 = require("./option");
exports.opt = option_1.default;
const version = require('../package.json').version;
exports.version = version;
